/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWorkflowsRouteImport } from './routes/app/workflows'
import { Route as AppUploadsRouteImport } from './routes/app/uploads'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppMemoryRouteImport } from './routes/app/memory'
import { Route as AppMedicalRouteImport } from './routes/app/medical'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppWorkflowsIdRouteImport } from './routes/app/workflows.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadsRoute = AppUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalRoute = AppMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsIdRoute = AppWorkflowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWorkflowsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/chat': typeof AppChatRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/uploads': typeof AppUploadsRoute
  '/app/workflows': typeof AppWorkflowsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/workflows/$id': typeof AppWorkflowsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/chat': typeof AppChatRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/uploads': typeof AppUploadsRoute
  '/app/workflows': typeof AppWorkflowsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/workflows/$id': typeof AppWorkflowsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/chat': typeof AppChatRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/uploads': typeof AppUploadsRoute
  '/app/workflows': typeof AppWorkflowsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/workflows/$id': typeof AppWorkflowsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/app/admin'
    | '/app/analytics'
    | '/app/audit'
    | '/app/chat'
    | '/app/medical'
    | '/app/memory'
    | '/app/settings'
    | '/app/uploads'
    | '/app/workflows'
    | '/app/'
    | '/app/workflows/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/app/admin'
    | '/app/analytics'
    | '/app/audit'
    | '/app/chat'
    | '/app/medical'
    | '/app/memory'
    | '/app/settings'
    | '/app/uploads'
    | '/app/workflows'
    | '/app'
    | '/app/workflows/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/app/admin'
    | '/app/analytics'
    | '/app/audit'
    | '/app/chat'
    | '/app/medical'
    | '/app/memory'
    | '/app/settings'
    | '/app/uploads'
    | '/app/workflows'
    | '/app/'
    | '/app/workflows/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/uploads': {
      id: '/app/uploads'
      path: '/uploads'
      fullPath: '/app/uploads'
      preLoaderRoute: typeof AppUploadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medical': {
      id: '/app/medical'
      path: '/medical'
      fullPath: '/app/medical'
      preLoaderRoute: typeof AppMedicalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows/$id': {
      id: '/app/workflows/$id'
      path: '/$id'
      fullPath: '/app/workflows/$id'
      preLoaderRoute: typeof AppWorkflowsIdRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
  }
}

interface AppWorkflowsRouteChildren {
  AppWorkflowsIdRoute: typeof AppWorkflowsIdRoute
}

const AppWorkflowsRouteChildren: AppWorkflowsRouteChildren = {
  AppWorkflowsIdRoute: AppWorkflowsIdRoute,
}

const AppWorkflowsRouteWithChildren = AppWorkflowsRoute._addFileChildren(
  AppWorkflowsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppChatRoute: typeof AppChatRoute
  AppMedicalRoute: typeof AppMedicalRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadsRoute: typeof AppUploadsRoute
  AppWorkflowsRoute: typeof AppWorkflowsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppChatRoute: AppChatRoute,
  AppMedicalRoute: AppMedicalRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadsRoute: AppUploadsRoute,
  AppWorkflowsRoute: AppWorkflowsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
